#########################################################################
# Title:            Saltbox: A-Train                                   #
# Author(s):        Salty, TABLE                                        #
# URL:              https://github.com/saltyorg/Saltbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- name: Settings | Check if `{{ a_train_paths_config_location | basename }}` exists
  stat:
    path: "{{ a_train_paths_config_location }}"
  register: a_train_config

- name: Settings | New `{{ a_train_paths_config_location | basename }}` tasks
  block:

    - name: Settings | Import default `{{ a_train_paths_config_location | basename }}`
      template:
        src: a-train.toml.j2
        dest: "{{ a_train_paths_config_location }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0775

  when: not a_train_config.stat.exists

- name: Settings | Check if `{{ a_train_paths_sa_location | basename }}` exists
  stat:
    path: "{{ a_train_paths_sa_location }}"
  register: a_train_sa

- name: "Fail when 'accounts.json' is not present"
  fail:
    msg: "You need to setup your service accounts file. Create a service account, add it to the team drives you wish to monitor and put the json file as 'accounts.json' in `{{a_train_paths_location}}`"
  when: not a_train_sa.stat.exists


